apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-cost-service
  namespace: monitoring
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/aws-cost-service-role
  labels:
    app: aws-cost-service
